# Generated by Django 3.2.13 on 2022-06-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=50, null=True)),
                ('publication', models.CharField(max_length=255, null=True)),
                ('no_of_copies', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
