# Generated by Django 3.2.13 on 2022-06-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('password', models.TextField()),
                ('role', models.CharField(choices=[('ADMIN', 'ADMIN'), ('USER', 'USER')], max_length=20)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
